<a href="https://colab.research.google.com/github/adhalifz-zen/Analisis-sentimen-menggunakan-SVM/blob/main/Crawl_data_twitter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Crawl Data Twitter > 2000 Tweets

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#@title Twitter Auth Token

twitter_auth_token = 'edcc7add49e8384a6f36e3664dbb8925f4009221' # change this auth token

In [ ]:
# Import required Python package
!pip install pandas

# Install Node.js (because tweet-harvest built using Node.js)
!sudo apt-get update
!sudo apt-get install -y ca-certificates curl gnupg
!sudo mkdir -p /etc/apt/keyrings
!curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

!NODE_MAJOR=20 && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list

!sudo apt-get update
!sudo apt-get install nodejs -y

!node -v

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Hit:1 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:5 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:6 https://deb.nodesource.com/node_20.x nodistro InRelease
Hit:7 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Ign:8 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:9 https://r2u.stat.illinois.edu/ubuntu jammy Release
Hit:10 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:11 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:12 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ca-certificates is already the newest version (20240203~22.04.1).
curl is already the newest version (7.81.0-1ubuntu1.18).
gnupg is already the newest version (2.2.27-3ubuntu2.1).
0 upgraded, 0 newly installed, 0 to remove and 49 not upgraded.
gpg: cannot open '/dev/tty': No such device or address
curl: (23) Failed writing body
deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main
Hit:1 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:3 https://deb.nodesource.com/node_20.x nodistro InRelease
Hit:4 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy InRelease
Ign:6 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:7 https://r2u.stat.illinois.edu/ubuntu jammy Release
Hit:8 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:9 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:10 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:11 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:12 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
nodejs is already the newest version (20.17.0-1nodesource1).
0 upgraded, 0 newly installed, 0 to remove and 49 not upgraded.
v20.17.0

In [ ]:
# Crawl Data

filename = 'kendaraanlistrik.csv'
search_keyword = 'kendaraan listrik since:2023-10-03 until:2024-10-03 lang:id'
limit = 1500

!npx -y tweet-harvest@2.6.1 -o "{kendaraan listrik}" -s "{kendaraan listrik}" --tab "LATEST" -l {limit} --token {twitter_auth_token}

⠙⠹⠸⠼⠴⠦Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1) (2)
Filling in keywords: kendaraan listrik since:2023-10-03 until:2024-10-03 lang:id

 (3)Created new directory: /content/tweets-data


Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 20

-- Scrolling... (1) (2) (3) (4)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 39

-- Scrolling... (1) (2) (3)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 58

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 73


Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 85

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 105

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 114

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 123

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 142

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 161

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 180

-- Scrolling... (1) (2) (3) (4) (5)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 197

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 215

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 234

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 249

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 267

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 287

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 307

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 326

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 346

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 365

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 382

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 399

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 418

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 437

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 457

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 473

-- Scrolling... (1) (2) (3)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 491

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 509

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 524

-- Scrolling... (1) (2) (3) (4)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 543

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 563

-- Scrolling... (1) (2) (3) (4)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 579

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 594

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 610

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 629

-- Scrolling... (1) (2)[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@b5aec2e076a97c91ede086e278ffe831"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@55b112ff96d9490b04bc9e723fc645cd"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@bd74f5bbd2edf4b5edc4edab0c74cda3"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@720c0bcc8d71ae6dfeca0232376198b6"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@e5a513e3fef59cd8f64c3cc6344ed2a2"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@7a8a2a681feaf784dc11c3299714459a"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@f59cd41d6e2b8374a217624fd21d458c"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@cf452692b3e583132dc78ffeef8ef13b"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@49352dccf1fb18a3de0e093963b1e4c5"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@699d3ce86602d3f67e33b52a02305c61"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.


Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 647

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 666

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 683

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 690

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 702

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 714

-- Scrolling... (1) (2) (3)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 727

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 737

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 744


Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 749

--Taking a break, waiting for 10 seconds...


Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 756

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 761


Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 768

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 778

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 782

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 800

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 819

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 838

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 855

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 874

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 891

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 911

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 923

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 937

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 949

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 967

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 986

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 1004

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 1021

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 1041

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 1061

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 1076

--Taking a break, waiting for 10 seconds...


Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 1091

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 1110

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 1128

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 1145

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 1159

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 1176

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 1196

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1) (2)[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@d184a05af00e8d5ed70e8d546e7385b0"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@8ef0c42f82cb9777bccf776cc55ed8c6"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@9312672e88b542da600148dfac1e634f"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@28c1c88a42eeb6dc81b3f8fd93dc1dd9"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@d6d434aff862f5abad46e8af72267a78"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@6f9b76be837b5324f75d8f9cbf8f1bd3"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@2f7f8ab352cb7720d00ce65d67b5058e"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@fa579ae62f5a60687fd7af7805aa45c6"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@5d84e2f2d732d9f16a7ebe13cc4e918f"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@e697a5074a4959d1fff5db289b7d469a"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@fdf6aebc1126094f9c4821299fac5516"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.


Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 1215

-- Scrolling... (1) (2) (3)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 1234

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 1254


Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 1272


Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 1290

-- Scrolling... (1) (2) (3)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 1308

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 1328

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 1347

-- Scrolling... (1) (2) (3) (4) (5) (6)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 1365

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 1385

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 1402

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 1420

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1) (2) (3)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 1438

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 1455

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 1474

-- Scrolling... (1) (2) (3) (4)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 1493

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/kendaraanlistrik.csv
Total tweets saved: 1505
Got 1505 tweets, done scrolling...
⠙

In [ ]:
import pandas as pd

# Specify the path to your CSV file
file_path = "/content/drive/MyDrive/SKRIPSI/kendaraanlistrik (2).csv"

# Read the CSV file into a pandas DataFrame
df = pd.read_csv(file_path, delimiter=",")

# Display the DataFrame
df

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1841619712553451985,Wed Oct 02 23:22:09 +0000 2024,0,Mercedes &amp; BMW Desak Jerman Tolak Tarif Ke...,1841619712553451985,NaN,NaN,in,Jakarta,0,0,0,https://x.com/BloombergTZ/status/1841619712553...,1582972008479920129,BloombergTZ
1,1841615001469206764,Wed Oct 02 23:03:26 +0000 2024,14,Presiden Jokowi menegaskan bahwa IKN akan meng...,1841615001469206764,https://pbs.twimg.com/media/GY67FVkbAAAKKH4.jpg,NaN,in,NaN,4,5,10,https://x.com/Nidyna10/status/1841615001469206764,1710309382293004288,Nidyna10
2,1841610369812595140,Wed Oct 02 22:45:02 +0000 2024,240,Dah jelas ya knp PEMERINTAH ngotot kendaraan l...,1841610369812595140,https://pbs.twimg.com/media/GY623P4bAAEZfTa.jpg,NaN,in,~#,6,41,123,https://x.com/papa_loren/status/18416103698125...,1466651308102877187,papa_loren
3,1841363651829317946,Wed Oct 02 16:05:31 +0000 2024,0,@SoftWarNews Ooooooo pak luhut kemaren nyuruh ...,1841509829384528272,NaN,SoftWarNews,in,NaN,0,0,0,https://x.com/tirtakbayarin/status/18415098293...,1369048527846838272,tirtakbayarin
4,1841476370746224957,Wed Oct 02 13:52:34 +0000 2024,7,Moeldoko Tetap Kawal Proyek Baterai Kendaraan ...,1841476370746224957,NaN,NaN,in,Jakarta,3,32,0,https://x.com/liputan6dotcom/status/1841476370...,47596019,liputan6dotcom
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1500,1829174196846682567,Thu Aug 29 15:08:07 +0000 2024,0,Samsung SDI dan GM Jalin Kerja Sama Bakal Bang...,1829174196846682567,NaN,NaN,in,"Jakarta, Indonesia",0,0,0,https://x.com/otosia/status/1829174196846682567,117686358,otosia
1501,1829170922986844364,Thu Aug 29 14:55:07 +0000 2024,0,BRARTI YOONGI LOE YANG KRIMINAL ITU HARUS ADA ...,1829170922986844364,NaN,NaN,in,NaN,0,0,0,https://x.com/sunfloowwerrr/status/18291709229...,1496277170250911744,sunfloowwerrr
1502,1829170261306036608,Thu Aug 29 14:52:29 +0000 2024,0,Pemerintah membantu 34 unit motor trail elektr...,1829170261306036608,https://pbs.twimg.com/media/GWKEUK5XIAAa9qt.jpg,NaN,in,NaN,0,1,0,https://x.com/conceplt/status/1829170261306036608,906666763361718272,conceplt
1503,1829128296912871522,Thu Aug 29 14:47:19 +0000 2024,4,@titobawono @gagitugung @PernebangRoket Lah ti...,1829168960094515630,https://pbs.twimg.com/media/GWKDdnAasAEWgEM.jpg,titobawono,in,WFH,0,1,0,https://x.com/nanaluve06/status/18291689600945...,1572759860352937984,nanaluve06
1504,1829164785151422748,Thu Aug 29 14:30:43 +0000 2024,0,2006 &amp; 2008 pergi ke Tembagapura di Papua ...,1829164785151422748,NaN,NaN,in,"ÜT: -7.99478,112.63367",0,1,0,https://x.com/RakantaRifky/status/182916478515...,232734217,RakantaRifky

In [ ]:
# Cek jumlah data yang didapatkan

num_tweets = len(df)
print(f"Jumlah tweet dalam dataframe adalah {num_tweets}.")

Jumlah tweet dalam dataframe adalah 1505.

In [ ]:
# prompt: ambil kolom full_text

df = df['full_text']
df

0       Mercedes &amp; BMW Desak Jerman Tolak Tarif Ke...
1       Presiden Jokowi menegaskan bahwa IKN akan meng...
2       Dah jelas ya knp PEMERINTAH ngotot kendaraan l...
3       @SoftWarNews Ooooooo pak luhut kemaren nyuruh ...
4       Moeldoko Tetap Kawal Proyek Baterai Kendaraan ...
                              ...
1500    Samsung SDI dan GM Jalin Kerja Sama Bakal Bang...
1501    BRARTI YOONGI LOE YANG KRIMINAL ITU HARUS ADA ...
1502    Pemerintah membantu 34 unit motor trail elektr...
1503    @titobawono @gagitugung @PernebangRoket Lah ti...
1504    2006 &amp; 2008 pergi ke Tembagapura di Papua ...
Name: full_text, Length: 1505, dtype: object

In [ ]:
# prompt: simpan hasilnya ke excel

# Save the DataFrame to an Excel file
excel_file_path = "/content/drive/MyDrive/SKRIPSI/kendaraanlistrik.xlsx"  # Specify the desired path and filename for the Excel file
df.to_excel(excel_file_path, index=False)  # Save to Excel, set index=False to avoid saving the index column